# Generated by Django 6.0.3 on 2026-06-09 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileTree', '0002_folder_user'),
        ('FlashCards', '0002_alter_sourcedocument_file_decksession'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='source_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_decks', to='FileTree.file'),
        ),
    ]
