# Generated by Django 6.0.3 on 2026-06-15 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "excel_subjects",
                    models.TextField(
                        blank=True, help_text="Subjects the user excels at", null=True
                    ),
                ),
                (
                    "poor_subjects",
                    models.TextField(
                        blank=True,
                        help_text="Subjects the user does poorly at",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Agent notes about the user", null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_memory",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
