# Generated by Django 6.0.3 on 2026-06-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmemory',
            name='flashcard_points',
            field=models.IntegerField(default=0),
        ),
    ]
