# Generated by Django 6.0.3 on 2026-06-16 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0002_agentmemory_flashcard_points'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentmemory',
            name='flashcard_points',
        ),
        migrations.AlterField(
            model_name='agentmemory',
            name='excel_subjects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agentmemory',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agentmemory',
            name='poor_subjects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FlashcardPointLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=1)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_point_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
