# Generated by Django 6.0.3 on 2026-06-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Agents", "0003_remove_agentmemory_flashcard_points_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentmemory",
            name="consumed_tokens",
            field=models.IntegerField(default=0),
        ),
    ]
