# Generated by Django 6.0.3 on 2026-06-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Agents", "0004_agentmemory_consumed_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="flashcardpointlog",
            name="flashcard_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
