# Generated by Django 6.0.3 on 2026-06-08 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ('FileTree', '0002_folder_user'),
    ('FlashCards', '0002_alter_sourcedocument_file_decksession'),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(related_name='user_groups', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FileTree.file')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_files', to='UserGroups.usergroup')),
            ],
            options={
                'unique_together': {('group', 'file')},
            },
        ),
        migrations.CreateModel(
            name='GroupDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlashCards.deck')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_decks', to='UserGroups.usergroup')),
            ],
            options={
                'unique_together': {('group', 'deck')},
            },
        ),
    ]
