# Generated by Django 6.0.3 on 2026-06-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserGroups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdeck',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='groupfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
