# Generated by Django 6.0.3 on 2026-05-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileTree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
