# Generated by Django 6.0.3 on 2026-05-05 18:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PomodoroSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('ended', 'Ended'), ('abandoned', 'Abandoned')], default='draft', max_length=16)),
                ('focus_time', models.PositiveIntegerField(default=1500, validators=[django.core.validators.MinValueValidator(1)])),
                ('break_time', models.PositiveIntegerField(default=300, validators=[django.core.validators.MinValueValidator(1)])),
                ('long_break_time', models.PositiveIntegerField(default=900, validators=[django.core.validators.MinValueValidator(1)])),
                ('cycles_before_long_break', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)])),
                ('auto_start', models.BooleanField(default=False)),
                ('total_focus_time', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_break_time', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('completed_pomodoros', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('points', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pomodoro_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pomodoro_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PomodoroTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('estimated_pomodoros', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('actual_pomodoros', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('completed', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='pomodoro.pomodorosession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pomodoro_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pomodoro_tasks',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pomodorosession',
            index=models.Index(fields=['user'], name='pomodoro_se_user_id_2e4068_idx'),
        ),
        migrations.AddIndex(
            model_name='pomodorosession',
            index=models.Index(fields=['start_time'], name='pomodoro_se_start_t_58ce12_idx'),
        ),
        migrations.AddIndex(
            model_name='pomodorosession',
            index=models.Index(fields=['status'], name='pomodoro_se_status_14f56a_idx'),
        ),
        migrations.AddIndex(
            model_name='pomodorotask',
            index=models.Index(fields=['session'], name='pomodoro_ta_session_661781_idx'),
        ),
        migrations.AddIndex(
            model_name='pomodorotask',
            index=models.Index(fields=['user'], name='pomodoro_ta_user_id_1009ef_idx'),
        ),
        migrations.AddIndex(
            model_name='pomodorotask',
            index=models.Index(fields=['display_order'], name='pomodoro_ta_display_2c59ba_idx'),
        ),
    ]
